version: "3.8"

services:
  app:
    build:
      context: ./app
    container_name: funasr-app
    ports:
      - "7860:7860" # 映射 Gradio 默认端口
    depends_on:
      - elasticsearch
    volumes:
      - ./app:/app # 挂载应用代码，方便调试
      - ./documents:/app/documents # 挂载文档目录到容器内
      - ./modelscope_cache:/root/.cache/modelscope # 挂载 modelscope 缓存目录
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # 挂载所有 GPU
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200" # Elasticsearch API 端口
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
